spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        mode: never
        continue-on-error: false
#        data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist


server:
  port: 8005

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
      secret: d2ZlcmFlcmZhZXJndzRydGdyd2d0cmd0Z2JydGd3NHJld3RncnRnZXJnZXJncmFnZXJnZXJnZmU=
      access: 3600000
      refresh: 2592000000
springdoc:
  override-with-generic-response: false